# adapted from http://conda.pydata.org/docs/travis.html
language: python
python:
 # We don't actually use the Travis Python, but this keeps it organized.
 - "2.7"
 - "3.5"

# switch to new infrastructure
sudo: false

before_install:
 # download and install miniconda
 - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/conda
 - export PATH="$HOME/conda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda config --add channels conda-forge
 - conda update -q conda

 # install essentials for deployment
 - conda install -f  setuptools
 - conda install -q conda-build
 - conda install -q anaconda-client

 # Useful for debugging any issues with conda
 - conda info -a

 # create and activate the build/test environment
 - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
 - source activate tenv

install:
 # Necessary dependencies
 - conda install -q tqdm numpy pytest pytest-cov codecov

 # Install the most recent rdkit package from the RDKit anaconda channel.
 - conda install -q -c rdkit rdkit


before_script:
 # RDKit
 - export RDBASE=$CONDA_PREFIX/Library/share/RDKit
 - echo $RDBASE

script:
 # Run tests
 - python -m pytest --cov=./ tests/test_methods.py tests/test_helpers.py tests/test_fusions.py tests/test_fingerprints.py tests/test_analysis.py

after_script:
- curl -s https://codecov.io/bash

before_deploy:
 - conda install -f  setuptools
 - conda build conda_recipe -c local

deploy:
  # Deploy to Anaconda.org
    provider: script
    script: anaconda -t $CONDA_UPLOAD_TOKEN  upload  --skip -u NostrumBioDiscovery $HOME/conda/conda-bld/**/analogs_finder-*.tar.bz2
    skip_cleanup: true
    on:
tags: true

